### ISSUE TITLE
Ctrl+J shortcut is already taken

### ISSUE THREAD

**Issue by jasononeil** [hamdanjaveed/Join-Lines#1]
Hi, thanks for the extension!

It seems that Ctrl+J is already taken by the "Jump to Definition" command in the default brackets.  Any chance of changing it to a different, non-conflicting shortcut?

(Or, you could even just add another non-conflicting shortcut, and leave Ctrl+J if that is what you are used to).

I personally use `Ctrl+Shift+J` for join lines, and `Ctrl+Alt+J` for join lines without whitespace.

**Comment by hamdanjaveed** [comment]
The extension's been updated to use your shortcuts instead :P

**Comment by jasononeil** [comment]
Thanks, that was fast :D
